---
  - hosts: loadbalancer
    tasks:
      - name: install the latest version of nginx
        yum:
          name: nginx
          state: latest
        become: yes

  - hosts: database
    become: yes
    tasks:
      - name: Install MySQL 5.7 repo
        yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm state=present

      - name: Install MySQL 5.7
        yum: pkg={{ item }}
        with_items:
        - mysql-community-server
        - mysql-community-client
        - MySQL-python

  - hosts: webserver
    become: true
    tasks:
      - name: install web components
        yum: name={{item}} state=present update_cache=yes
        with_items:
          - apache2
          - libapache2-mod-wsgi
          - python-pip
          - python-virtualenv